### ISSUE TITLE
Adding Genetic Chickengineering to Addons

### ISSUE THREAD

**Issue by kii-chan-reloaded** [Slimefun/Wiki#109]
## Description
I would like to add my plugin to the Third-party section of the addons page.

## Addon Resources (if applicable)
https://github.com/kii-chan-reloaded/GeneticChickengineering

Genetic Chickengineering (GCE) is a mid- to late-game, resource-generating plugin heavily inspired by the Forge mod Chicken. GCE allows players to selectively breed special chickens to passively produce various vanilla resources, plus some Slimefun resources (mostly metal ore dusts).

## Wiki page (If applicable)
Addons

## Slimefun Version
Built on RC-19, gameplay tested on current dev (805)

**Comment by TheBusyBiscuit** [comment]
Added 👍🏻 
This also looks really cool btw :)

Btw: You don't need to create an issue for your addon to be added, you can also just make a PR directly.

**Comment by kii-chan-reloaded** [comment]
Thank you for adding it! For what it's worth, the addon page and the developer guide have different instructions on how to add a new addon to the list. The addon page itself says to submit an issue like this, whereas the final section of the developer guide mentions the pull request method. I chose the addon page's suggestion since I assumed it was being updated more frequently. If the PR method is preferred, I'll submit a PR to make the two pages agree on that.
