### ISSUE TITLE
Low TPS, CargoNetwork issue, 

### ISSUE THREAD

**Issue by ScrollDP** [Slimefun/Wiki#176]
Hi, I have a problem with my plugins from slimefun, Some addons slow down the server. Question is, How can I limit some things, and optimize slimefun.
Here is the report from spark: https://spark.lucko.me/dcqBZ5B1HV
And here from timings: https://timings.pl3x.net/?id=a15a586e683a43cd8edabdc8c1afd7a3#plugins
And here is list of plugins: https://docs.google.com/spreadsheets/d/1pbjJNEiCS_xe6-gkDvhUGa8D5braUpWU65BIDUNXUzI/edit?usp=sharing
Any help can help me. Thanks :)

**Comment by WalshyDev** [comment]
ChestTerminal is known to cause lag and that's the case here. Regardless, wrong place to report this.

**Comment by ScrollDP** [comment]
Oh, thanks, I will delete this addon and see if can be better. In the future, where I must write reports? Because, I can't find, where I can post it. :)

**Comment by WalshyDev** [comment]
Well, Slimefun's repo is https://github.com/Slimefun/Slimefun4 however going to Discord first is recommended. Discord: https://discord.gg/slimefun
