### ISSUE TITLE
There is no "Pickaxe Of Containment" in the tools section      (its what the pickaxe of containment wiki said.)

### ISSUE THREAD

**Issue by spacxen** [Slimefun/Wiki#199]

**Comment by Phoenix-Starlight** [comment]
Are you certain that it doesn't exist?
According to the source here and at the Wiki section for the code base, it exists, and has its own page.
https://github.com/Slimefun/Wiki/blob/master/pages/Tools.md
https://github.com/Slimefun/Slimefun4/wiki/Tools
https://github.com/Slimefun/Slimefun4/wiki/Pickaxe-of-Containment
https://github.com/Slimefun/Wiki/blob/master/pages/Tools.md

**Comment by spacxen** [comment]
yeah but when i go in the server and i look through the book and look in the tools section
it isnt there

**Comment by Phoenix-Starlight** [comment]
It may be disabled, could you take your problem to the Discord server? It makes it easier to help.
