### ISSUE TITLE
Adding DynaTech to Addons

### ISSUE THREAD

**Issue by ProfElements** [Slimefun/Wiki#89]
## Description
I would like my addon to be added Third Party Addons section.

## Addon Resources (if applicable)
https://github.com/profelements/dynatech

My addons currently adds 5 things, the most nice being a item that autofeeds you food or CustomFood from ExoticGarden
Have a Garden Cloche type block that automatically grows items so that Its not as laggy to make large automated farms.

## Wiki page (If applicable)
Addons

## Slimefun Version
DEV - 767

**Comment by WalshyDev** [comment]
You will need to setup a bug tracker link before we merge - https://github.com/ProfElements/ExtraStuff/blob/master/src/main/java/me/profelements/extrastuff/ExtraStuff.java#L41

**Comment by ProfElements** [comment]
Thank you for the feedback I just made the necassary changes,
